name: Release to Google Play

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Decode Keystore File
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > /tmp/keystore.jks

      - name: Build Android Release
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease --no-daemon
        env:
          KEYSTORE_FILE: /tmp/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: ./android/app/build/outputs/
      # - name: Upload Release to Google Play
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
      #     packageName: com.your.app.package
      #     releaseFile: android/app/build/outputs/bundle/release/app-release-signed.aab
      #     track: production
      #     inAppUpdatePriority: 0
      #     whatsNewDirectory: distribution/whatsnew
